name: 'Prepare node'
description: 'Prepares node by installing node + dependencies'

runs:
  using: 'composite'
  steps:
    - name: checkout repository
      uses: actions/checkout@v3

    - name: setup node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: install node packages
      run: npm ci
      shell: bash